/**
 * Unified backend field length constraints.
 * Keep these values aligned with frontend/src/constants/fieldConstraints.ts.
 */
export const FIELD_MAX_LENGTH = {
  NAME: 64,
  GROUP: 64,
  DOMAIN: 255,
  HOSTNAME: 255,
  REGISTRAR: 128,
  CLOUDFLARE_ZONE_ID: 128,
  URL: 512,
  API_KEY: 256,
  API_SECRET: 256,
  NOTES: 1000,
  REASON: 300,
  CAMPAIGN_ID: 64,
  TRAFFIC_ENTRY_VALUE: 255,
  USER_AGENT_VALUE: 1000,
  CAMPAIGN_ALIAS: 64,
  UNIQUE_PARAMETER: 64,
  PARAMETER_ALIAS: 64,
  PARAMETER_NAME: 64,
  PARAMETER_VALUE: 256,
  ROUTING_RULE_NAME: 80,
  ROUTING_RULE_DESCRIPTION: 300,
  ROUTING_REDIRECT_URL: 512,
  ROUTING_BLOCK_REASON: 200,
  ROUTING_TEST_VALUE: 128,
  ROUTING_TEST_REFERRER: 512,
} as const;

