-- Migration: 扩展clicks表的sub_id字段从5个到30个
-- Date: 2026-04-07
-- Purpose: 对标Keitaro的完整Sub ID支持(sub1-sub30)
-- Description:
--   原始clicks表只有sub_id_1到sub_id_3 (或sub_id_1到sub_id_5)
--   本迁移添加缺失的sub_id字段，扩展到完整的30个Sub ID
--   所有新字段使用TEXT类型和DEFAULT NULL, 确保向后兼容

-- 添加缺失的sub_id字段 (sub6到sub30)
ALTER TABLE clicks ADD COLUMN sub_id_4 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_5 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_6 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_7 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_8 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_9 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_10 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_11 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_12 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_13 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_14 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_15 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_16 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_17 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_18 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_19 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_20 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_21 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_22 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_23 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_24 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_25 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_26 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_27 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_28 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_29 TEXT DEFAULT NULL;
ALTER TABLE clicks ADD COLUMN sub_id_30 TEXT DEFAULT NULL;

-- 创建索引以优化查询性能 (可选, 根据实际查询需求)
-- CREATE INDEX IF NOT EXISTS idx_clicks_sub_id_6 ON clicks(sub_id_6);
-- CREATE INDEX IF NOT EXISTS idx_clicks_sub_id_7 ON clicks(sub_id_7);
-- ... 其他索引根据需要添加
